### ISSUE TITLE
Handle 429 response

### ISSUE THREAD

**Issue by mdharamadas** [RetailMeNot/TestRailSDK#22]
With recent upgrade to TestRail API, the API is rate limited on TestRail Hosted and may throttle requests. TestRail might also return a 429 Too Many Requests response which the users are expected to handle. Such a response also includes a Retry-After header indicating how many seconds to wait before allowed to submit the next request.

The SDK needs to be updated to handle this response and retry the request based on the Retry-After header value.

**Comment by vinceis1337** [comment]
I have insufficient access so I cannot add mdharamadas as the assignee for this issue. 
However, let it be noted that he is working on this issue himself.

**Comment by vinceis1337** [comment]
https://github.com/RetailMeNot/TestRailSDK/pull/23
