### ISSUE TITLE
Please merge my pull requests with critical fixes to master.

### ISSUE THREAD

**Issue by sfranchuk** [RetailMeNot/TestRailSDK#43]
Please merge my pull requests with critical fixes to master. 
https://github.com/RetailMeNot/TestRailSDK/pull/41
https://github.com/RetailMeNot/TestRailSDK/pull/42
This is very important for me and my team.

Best Regards, Sergey Franchuk.

**Comment by vinceis1337** [comment]
Sorry for the delay @sfranchuk I am on vacation in India. I will get you the updates ASAP

**Comment by vinceis1337** [comment]
TestRailSDK 1.2 has been released. It may take some time for the Central Repository to show it as available.

<img width="1132" alt="screen shot 2016-12-22 at 4 11 36 pm" src="https://cloud.githubusercontent.com/assets/5994871/21442102/5d5d1064-c861-11e6-847a-92bb79dcb5fa.png">

**Comment by sfranchuk** [comment]
Thank you so much for your help.
